[[plugins]]
package = "netlify-plugin-flutter"
   [plugins.inputs]
    channel = "stable"
[build]
command = "flutter build web --release --dart-define=ENDPOINT=dazzdice-server.nerissaarvna.repl.co --dart-define=ENDPOINT2=flea-sought-maggot.ngrok-free.app"
publish = "build/web"